### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by alterphp** [vgaugler/test-api-Symfony5-Twig#1]
Hi Victor,

As asked, here is my first feedback, only based on controllers for now :
- You should separate API controllers from controller rendering HTML pages
- Routing URLs are inconsistent, controller methods as well (separating API from pages controllers will help)
- Naming of variables is **very important**, for example : `$movie` should not be used to store a collections of Movie objects, `$movies` is better
- Routes returning "all" movies (or any "all" stuffs) MUST be paginated => when the DB will gain more and more records, you can not afford to return every ones ;-)

**Comment by vgaugler** [comment]
thank you very much for your review. I'll fix that asap before you see the rest! 

- You should separate API controllers from controller rendering HTML pages
      <p>  i discovered that in challenge project </p>
- Routing URLs are inconsistent, controller methods as well (separating API from pages controllers will help)     
- Naming of variables is very important, for example : $movie should not be used to store a collections of Movie objects, $movies is better
    <p> ah I was stupid to have shared it like that, the right name is the basis. I was so impatient and excited to find symfony that I forgot 
    to fix it   :( </p>
- Routes returning "all" movies (or any "all" stuffs) MUST be paginated => when the DB will gain more and more records, you can not afford to return every ones ;-)
    <p> sure , I will fix it ! </p>

**Comment by vgaugler** [comment]
done
